server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/amigoscode_fraud
    username: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true